server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
BaseRemote:
  ribbon:
    ## 服务提供者的地址，不是服务注册中心的地址
    listOfServers: http://localhost:8088
spring:
  application:
    name: pc-web
