server:
  port: 8761

eureka:
  instance:
    hostname: 119.3.11.44
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
