server:
  port: 8761

eureka:
  instance:
    hostname: 106.14.140.238
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://119.3.11.44:8761/eureka/
