server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://119.3.11.44:8761/eureka/
    fetch-registry: false
spring:
  application:
    name: share
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   password: Hewenxing4316@
   url: jdbc:mysql://106.14.140.238:3306/xxDesign?characterEncoding=utf-8
   username: root
  data:
   solr:
      host: http://106.14.140.238:8089/solr
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: xyz.hpwyx.pojo
